### ISSUE TITLE
Consumption of markdown

### ISSUE THREAD

**Issue by d4ncer** [movio/apidoc-ui#12]
Links of help:
- [Markdown parser](https://github.com/chjj/marked) - supports Github flavour
- [Injecting raw HTML in React](https://facebook.github.io/react/tips/dangerously-set-inner-html.html)

**Comment by jackhopner** [comment]
@d4ncer I've implemented it using https://github.com/rexxars/react-markdown

It's a lot simpler and all we have to do now is style the elements that it has generated, e.g. <code>

Was there a particular reason you picked that parser?

**Comment by d4ncer** [comment]
@jackhopner Awesome! Considerably easier than what I'd thought we'd have to do. Does it support GitHub specific syntax?

**Comment by d4ncer** [comment]
Add a MD component

**Comment by d4ncer** [comment]
Need to figure out a way to deal with syntactically incorrect upstream markdown.

<img width="781" alt="screen shot 2016-07-04 at 9 43 32 pm" src="https://cloud.githubusercontent.com/assets/1840377/16556865/8a10680c-4230-11e6-9e1a-58680ddfa8c3.png">

**Comment by d4ncer** [comment]
Implemented.
